version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 8000:80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
volumes:
  postgres_data: