apiVersion: v1
kind: ConfigMap
metadata:
  name: edunest-config
data:
  DEBUG: "0"
  SECRET_KEY: change_me
  ALLOWED_HOSTS: "edunest.francecentral.cloudapp.azure.com"
  CSRF_TRUSTED_ORIGINS: https://edunest.francecentral.cloudapp.azure.com
  SQL_ENGINE: django.db.backends.postgresql
  SQL_DATABASE: edunest
  SQL_USER: postgres
  SQL_PASSWORD: postgres
  SQL_HOST: db
  SQL_PORT: "5432"
  DATABASE: postgres

  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: edunest

  PGADMIN_DEFAULT_EMAIL: admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: admin
